name: Test release

on:
  workflow_dispatch:

jobs:
  do_release:
    name: try to bump
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: npm ci
        working-directory: ./.github/release

      - name: Git config
        run: |
          git config --local user.email 'hello@rive.app'
          git config --local user.name ${{ github.actor }}
      - name: Build release - Bump version number, update changelog, push and tag
        run: npm run release -- --ci
        working-directory: ./.github/release
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_GITHUB }}
